%YAML 1.2
---

# host infos
host_string: '10.73.73.105'
host_user: 'root'
host_pass: 'redhat'

# manually configured selenium hub
selenium_hub: ''

# avocado config
avocado_results_dir: '/home/weiwang/work/autowork/avocado-results'

# versions of pkg/sys under test
test_pkg_ver: 'cockpit-ovirt-dashboard-0.11.39'
test_sys_ver: 'rhvh-4.2.8.6-0.20190517.0'