%YAML 1.2
---

# host infos
host_string: '10.73.73.105'
host_user: 'root'
host_pass: 'redhat'

# manually configured selenium hub
selenium_hub: ''

# avocado config
avocado_results_dir: '/home/weiwang/work_autocode/cockpit_proj/avocado-results'

# versions of pkg/sys under test
test_pkg_ver: 'cockpit-ovirt-dashboard-0.12.3'
test_sys_ver: 'ovirt-node-ng-4.3.1-0.20190228'